name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install and Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.SELF_LEARNING_ENGLISH }}
          branch: master
          folder: docs/.vitepress/dist
          clean: true
          repository-name: woai3c/woai3c.github.io
          target-folder: self-learning-english
